### ISSUE TITLE
Matomo Maintenance Update

### ISSUE THREAD

**Issue by DreamTrims** [TokelPlatform/tokel_web#21]
Please update Matomo:
https://analytics.tokel.io/index.php?module=CoreHome&action=index&idSite=1&period=week&date=today#?idSite=1&period=month&date=2021-10-02&segment=&category=Dashboard_Dashboard&subcategory=1

Many thanks

**Comment by piggydoughnut** [comment]
I think @DreamTrims have already done this and has the access rights to make these updates himself
