### ISSUE TITLE
please update footer with new social links

### ISSUE THREAD

**Issue by DreamTrims** [TokelPlatform/tokel_web#5]
perhaps these could go at the **top** alongside Discord:
https://twitter.com/TokelPlatform
https://www.reddit.com/r/tokel/
https://t.me/TokelPlatform

For the **footer**:
https://www.facebook.com/TokelPlatform/
https://flote.app/user/Tokel
https://bittube.tv/profile/Tokel
https://www.linkedin.com/company/tokel/
https://www.youtube.com/channel/UCW9C_EuW54yOFArqJjRMJmQ

**Comment by piggydoughnut** [comment]
So these are the links are added. I can add more but then its getting a bit excessive. I chose those coz I think they are the most relevant, however I am happy to hear everyone else s thoughts on which ones are relevant. @DreamTrims @jorian @NutellaLicka 

<img width="1405" alt="Screen Shot 2021-07-28 at 9 57 52 PM" src="https://user-images.githubusercontent.com/2395326/127335134-56f4c985-5dd5-4ea6-b40f-4bab1ed34f9c.png">

**Comment by DreamTrims** [comment]
I see what you did, it makes sense
